# Generated by Django 6.0.5 on 2026-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_remove_subscription_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
